### PR TITLE
Add optional CNAME record creation for specified DNS zone

### PR DESCRIPTION
**Pull request by Sebor**
Closes https://github.com/terraform-yc-modules/terraform-yc-postgresql/issues/11
Also update README

### CODE REVIEW

**Comment by Sebor** [comment]
@patsevanton @romati88 hi!
Could you review this PR?

**Comment by adushein** [comment]
Hi @Sebor,
can you describe your case why do you need additional dns record? There are special FQDNs for such purposes https://cloud.yandex.com/en/docs/managed-postgresql/operations/connect#special-fqdns

If someone needs an extra dns record, all the necessary information for creating is available from module outputs

**Comment by Sebor** [comment]
> Hi @Sebor, can you describe your case why do you need an additional dns record? There are special FQDNs for such purposes https://cloud.yandex.com/en/docs/managed-postgresql/operations/connect#special-fqdns

It's just a cosmetic thing for conveniently remembering the cluster address. In some cases we want to recreate cluster but do not want to change applications config


> If someone needs an extra dns record, all the necessary information for creating is available from module outputs

That's true but, for example, with terragrunt you will need to define one more "module" additionally with single resource only. It looks acceptable, but isn't very pretty and is more verbose

**Comment by Sebor** [comment]
@adushein hi! Any news?

**Comment by Sebor** [comment]
@ezhische hi! Could you help with this PR?

**Review by adushein — APPROVED** [review]

**Pull request merged**
